### ISSUE TITLE
NERC model format

### ISSUE THREAD

**Issue by chopeen** [opener-project/nerc-fr#1]
Is it possible to use `nerc-fr.bin` as a classifier for Stanford NER (`edu.stanford.nlp.ie.NERServer` to be precise)?

Stanford NER uses `*.ser.gz` files (serialized Java objects, I think). Is there a way to convert the NERC model to this format?

**Comment by ragerri** [comment]
No,

It is not possible. You can use the NER models distributed by Stanford.

R

On Fri, Sep 16, 2016 at 1:42 PM, Marek Grzenkowicz <notifications@github.com

**Comment by chopeen** [comment]
I would, but I found no Stanford NER model for French.

Thanks for a prompt response, anyway!
